dist: trusty
language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE petclinic;'
cache:
 directories:
  - .autoconf
  - $HOME/ .m2
script: mvn test -Dspring.profiles.active=mysql-travis